
name: Build and Publish

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build with Gradle
      run: ./gradlew test build

    - name: Download file
      uses: timheuer/base64-to-file@v1.1
      with:
        fileName: 'oss_signing_key.gpg'
        fileDir: '.'
        encodedString: ${{ secrets.SIGNING_KEY }}
    - name: Publish
      env:
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        SECRET_RING_FILE: ${{ secrets.SIGNING_SECRET_KEY_RING_FILE }}
        SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
        SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
      run: ./gradlew publish
